In [1]:
import pandas as pd
import numpy as np

In [2]:
filepath = "data/visualization_data.csv"

df = pd.read_csv(filepath)
df.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,121,122,123,124,125,126,127,label,gender,emotions
0,0,-573.379150,34.064041,-33.337578,3.489916,-13.482152,-6.327230,-17.734171,-15.280939,-8.379515,...,-0.797864,-0.332338,0.177741,0.204333,-0.211895,0.080943,-0.274973,6,1,fearful
1,1,-545.244568,38.073475,-8.023163,7.236882,-13.688817,-2.157916,-12.315373,-7.948586,-14.858138,...,0.029629,-0.052548,-0.059842,-0.084479,0.181888,0.202147,-0.165808,5,1,angry
2,2,-690.535461,43.141396,-9.854416,10.819540,-14.295117,-2.288000,-10.151420,-4.941710,-6.615477,...,-0.174446,-0.116118,0.133232,0.191797,-0.322106,-0.287355,0.132173,8,1,surprise
3,3,-553.611633,41.233486,-9.912664,8.587062,-5.737630,-5.831647,-17.839375,-11.084945,-11.369494,...,0.068388,0.201094,-0.062219,-0.291406,-0.284542,0.070689,0.088307,6,1,fearful
4,4,-576.153442,49.947994,-13.857949,8.248825,-12.159565,0.193613,-8.719680,-7.731156,-8.692744,...,-0.723615,0.074101,0.027505,0.288559,-0.022368,0.053056,0.346106,5,1,angry

In [4]:

                       
emotion_group = df.groupby(["emotions"])

emotion_df = emotion_group.mean()
emotion_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,120,121,122,123,124,125,126,127,label,gender
emotions,,,,,,,,,,,,,,,,,,,,,
angry,2137.915541,-407.294143,46.228976,-14.125314,9.986737,-16.321601,3.010861,-13.496361,-5.919352,-14.672155,...,-0.161829,-0.121710,-0.089569,-0.032122,-0.041260,-0.091721,-0.078866,-0.067721,5.0,0.837838
calm,1949.055233,-558.141225,71.428269,1.669474,22.034680,-1.402906,7.117394,-9.512632,-4.065379,-11.306173,...,-0.473388,-0.269479,-0.128070,-0.267431,-0.096466,-0.180224,-0.298705,-0.010196,2.0,0.790698
disgust,2180.971284,-486.824552,73.186640,-0.306481,14.087307,-6.286525,4.795460,-13.322223,-2.637163,-14.358050,...,-0.101757,-0.050650,0.004619,0.068597,0.033138,-0.031450,-0.074469,-0.027220,7.0,0.837838
fearful,2157.484797,-424.823461,49.297719,-10.398084,11.226780,-9.197276,3.974172,-13.519639,-0.775171,-15.732408,...,-0.255778,-0.215943,-0.095298,0.005963,-0.078094,0.018520,-0.127845,0.030178,6.0,0.837838
happy,2135.108108,-441.373977,57.427686,-9.157630,13.635121,-9.597958,1.690689,-14.343496,-3.498941,-12.481020,...,-0.160669,-0.050618,-0.070520,0.042084,-0.064572,-0.026217,-0.062400,-0.046854,3.0,0.837838
sad,2116.971284,-522.125721,73.155978,11.770611,25.129184,0.135185,10.580438,-11.144357,-6.168417,-10.762968,...,-0.144265,-0.090233,-0.014517,-0.022826,-0.011423,-0.053544,-0.096845,-0.095935,4.0,0.837838
surprise,2186.633446,-456.208451,62.424134,-8.023625,6.589614,-12.175127,2.160547,-14.968454,-1.835755,-15.915858,...,-0.148838,-0.056872,-0.097030,0.054585,-0.050377,-0.008065,-0.081746,-0.043007,8.0,0.837838

In [5]:
emotion_df.to_csv("data/emotion_avg.csv", encoding='utf-8', index=True)